name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                color: 'good',
                title: "${{ github.repository }} #${{ github.event.number}}",
                title_link: "${{ github.event.pull_request.html_url }}",
                }],
                actions: [{
                }]
              }]
            }        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
