name: CI

on:
  pull_request:
    types: [opened, reopened, closed, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "${{ github.event.pull_request.author }} ${{ github.event.action }} <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} #${{ github.event.number }}>",
            }        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
